fall = {
    "Fall": True,
    "Leaves": True,
    "Tree": True,
    "Pumpkin": True,
    "Apple": True,
    "Acorn": True,
    "Corn": True,
    "Sweater": True,
    "Jacket": True,
    "Pinecone": True,
    "Harvest": True,
    "Squash": True,
    "Brown": True,
    "Yellow": True,
    "Orange": True,
    "Nuts": True,
    "Hayride": True,
    "Hay": True,
    "Owl": True,
    "Crow": True,
    "Scarecrow": True,
    "Football": True,
    "Game": True,
    "Moon": True,
    "Hay Bale": True,
    "Red": True,
    "Rake": True,
    "Gourd": True,
    "Sunflower": True,
    "Squirrel": True,
    "Leaf": True,
    "Branch": True,
    "Apple Tree": True,
    "Cider": True,
    "Preserves": True,
    "Seeds": True,
    "September": True,
    "October": True,
    "Autumn": True,
    "Cornstalk": True,
    "Wind": True,
    "Clouds": True,
    "Rain": True,
    "Candy Corn": True,
    "Bonfire": True,
    "Green": True,
    "Pilgrim": True,
    "Cornucopia": True,
    "Indian": True,
    "Quilt": True,
    "Ripe": True,
    "Festival": True,
    "Foliage": True,
    "Crisp": True,
    "Cozy": True,
    "Hike": True,
    "Brisk": True,
    "Crunchy": True,
    "Maize": True,
    "Season": True,
    "Equinox": True,
    "Frost": True,
    "Gold": True,
    "Woods": True,
    "Crackling": True,
    "Chili": True,
    "Scarf": True,
    "Cornstalks": True,
    "Cobweb": True,
    "School": True,
    "Bus": True,
    "Bountiful": True,
    "Crops": True,
    "Chestnuts": True,
    "Breezy": True,
    "Happy": True,
    "Reap": True,
    "Foggy": True
}

Marvel = { 
 
}